AmericanMedicalAssociation/AMA-style-guide

- styleguide/source/_patterns/01-molecules/05-navigation/07-ribbon-dropdown/_ribbon-dropdown.scss
- styleguide/source/_patterns/01-molecules/05-navigation/08-ribbon-user-menu/_ribbon-user-menu.scss
- styleguide/source/assets/js/nav.js
Ticket: https://issues.ama-assn.org/browse/EWL-3095
To test:
- Go to http://localhost:3000/?p=organisms-ribbon and http://localhost:3000/?p=organisms-ribbon-auth and review the style changes outlined in the ticket.
> EWL 3095 - Ribbon header cleanup

- styleguide/source/_patterns/01-molecules/05-navigation/08-ribbon-user-menu/_ribbon-user-menu.scss
> Remove box-shadow from ribbon user menu

- styleguide/source/_patterns/01-molecules/05-navigation/01-jump-nav/jump-nav.twig
- styleguide/source/_patterns/03-templates/02-article/article.twig
- styleguide/source/assets/js/jump-nav.js
Ticket: https://issues.ama-assn.org/browse/EWL-3113
To test:
- Go to http://localhost:3000/?p=templates-article
- Scroll down the page, the jump nav should stick once you reach the article content.
- As you scroll through each section, the jump nav should switch to whichever is actively shown (active is blue).
- If you click on a jump nav link, the page should smooth scroll to that section.
- At smaller viewports, the jump nav should collapse into a dropdown.
**_Note: I had to rework the jump nav js to work with the active state of the section and the smooth scroll._**
> EWL 3113 - Animate jump nav menu

- styleguide/source/_patterns/01-molecules/05-navigation/00-primary-nav/_primary-nav.scss
- styleguide/source/_patterns/01-molecules/05-navigation/01-jump-nav/_jump-nav.scss
- styleguide/source/_patterns/02-organisms/00-global/00-header-primary/_header-primary.scss
- styleguide/source/_patterns/02-organisms/00-global/00-header-primary/header-primary.twig
- styleguide/source/_patterns/02-organisms/00-global/03-ribbon/_ribbon.scss
- styleguide/source/_patterns/03-templates/02-article/article.twig
- styleguide/source/assets/js/jump-nav.js
- styleguide/source/assets/js/nav-primary.js
Ticket: https://issues.ama-assn.org/browse/EWL-3349
To test:
- Go to Template: Home and Article
- Scroll down on the page, the header will stick to the top of the page once you scroll past the header itself
- Check at all viewports to make sure it displays correctly
- Click on the menu items once you have scrolled down the page
- On the article page, make sure the jump nav is visible with the sticky nav
> EWL 3349 - Sticky header

- styleguide/source/_patterns/01-molecules/02-blocks/01-block-promo/_block-promo.scss
- styleguide/source/_patterns/01-molecules/02-blocks/01-block-promo/block-promo-orange.twig
- styleguide/source/_patterns/01-molecules/02-blocks/01-block-promo/block-promo-purple.twig
- styleguide/source/_patterns/01-molecules/02-blocks/01-block-promo/block-promo-red.twig
- styleguide/source/_patterns/01-molecules/02-blocks/01-block-promo/block-promo.twig
- styleguide/source/_patterns/02-organisms/03-sections/00-list-block-promo/00-list-block-promo.twig
Ticket: https://issues.ama-assn.org/browse/EWL-3253
* Navigate to the promo block list organism (http://localhost:3000/?p=organisms-list-block-promo) 
* Observe that there are three items that are equal
* Observe the first block is purple
* Observe the second block is red
* Observe the third block is yellow/orange
* Inspect and delete an item
* Observe they are 50:50
* Resize to mobile
* Observe there are margins 
* Observe the items are stacked on mobile
> Ewl 3253 promo refactor

- styleguide/source/_patterns/01-molecules/05-navigation/09-pagination-controls/_pagination-controls.scss
- styleguide/source/_patterns/01-molecules/05-navigation/09-pagination-controls/pagination-controls.mdown
- styleguide/source/_patterns/01-molecules/05-navigation/09-pagination-controls/pagination-controls.twig
- styleguide/source/assets/css/style.scss
Ticket: https://issues.ama-assn.org/browse/EWL-3265
To test:
- Go to Molecules > Navigation > Pagination Controls
- Ensure that it works at all viewport sizes.
> EWL 3265 - Pagination Controls

- styleguide/source/_patterns/00-atoms/04-images/01-landscape-3x2.twig
- styleguide/source/_patterns/01-molecules/06-components/11-hub-card/_hub-card.scss
- styleguide/source/_patterns/01-molecules/06-components/11-hub-card/hub-card-no-image.twig
- styleguide/source/_patterns/01-molecules/06-components/11-hub-card/hub-card.md
- styleguide/source/_patterns/01-molecules/06-components/11-hub-card/hub-card.twig
- styleguide/source/assets/css/style.scss
To Review look at Molecules > Components > Hub Card & Hub Card No Image
Note: The layouts that control the height and width of these components will be part of ticket number EWL-3369 so are not part of this ticket. for reviewing purposes you can put a max width on .hub-card if you want.
> Ewl 3366 hub card

- styleguide/source/_patterns/01-molecules/06-components/12-hub-cta/_hub-cta.scss
- styleguide/source/_patterns/01-molecules/06-components/12-hub-cta/hub-cta-half-left.md
- styleguide/source/_patterns/01-molecules/06-components/12-hub-cta/hub-cta-half-left.twig
- styleguide/source/_patterns/01-molecules/06-components/12-hub-cta/hub-cta-half.md
- styleguide/source/_patterns/01-molecules/06-components/12-hub-cta/hub-cta-half.twig
- styleguide/source/assets/css/style.scss
to test go to Molecules > Components > Hub CTA 50/50 and Hub CTA 50/50 left
> Begin markup and styles on the hub cat

- styleguide/source/_annotations/annotations.js
- styleguide/source/_patterns/01-molecules/00-text/00-article-header/article-header.md
- styleguide/source/_patterns/01-molecules/00-text/00-article-header/article-header.twig
- styleguide/source/_patterns/01-molecules/00-text/00-section-header/_section-header.scss
- styleguide/source/_patterns/01-molecules/00-text/00-section-header/section-header.md
- styleguide/source/_patterns/01-molecules/00-text/00-section-header/section-header.twig
- styleguide/source/_patterns/03-templates/02-article/article.twig
- styleguide/source/assets/css/scss/objects/_article.scss
- styleguide/source/assets/css/style.scss
Renames article-header to section-header.
> Ewl 3371 section divider

- styleguide/source/_patterns/01-molecules/06-components/10-hub-hero/_hub-hero.scss
- styleguide/source/_patterns/01-molecules/06-components/12-hub-cta/_hub-cta.scss
- styleguide/source/_patterns/01-molecules/06-components/12-hub-cta/hub-cta-half-left.twig
- styleguide/source/_patterns/01-molecules/06-components/12-hub-cta/hub-cta-half.twig
- styleguide/source/_patterns/02-organisms/03-sections/01-hub-card-row/hub-card-row.twig
- styleguide/source/_patterns/03-templates/03-hub/hub.twig
To Review go to Templates > Hub > Hub
Andy has reviewed this page and signed off with minimal feedback which was implemented in this ticket.
> Ewl 3372 hub template

- styleguide/source/_patterns/01-molecules/06-components/10-hub-hero/_hub-hero.scss
- styleguide/source/_patterns/01-molecules/06-components/12-hub-cta/_hub-cta.scss
- styleguide/source/_patterns/01-molecules/06-components/12-hub-cta/hub-cta-half-left.twig
- styleguide/source/_patterns/01-molecules/06-components/12-hub-cta/hub-cta-half.twig
- styleguide/source/_patterns/02-organisms/03-sections/01-hub-card-row/hub-card-row.twig
- styleguide/source/_patterns/03-templates/03-hub/hub.twig
- styleguide/source/_patterns/04-pages/01-hub-page/hub-page-2.twig
- styleguide/source/_patterns/04-pages/01-hub-page/hub-page-multiple-sections.twig
- styleguide/source/_patterns/04-pages/01-hub-page/hub-page-no-hero.twig
- styleguide/source/_patterns/04-pages/01-hub-page/hub-page.twig
To Review go to pages > Hub > and review the three different page examples in there.
There is no sample content, but this shows how the components might be combined to create three different pages.
**Please don't merge until EWL-3372 is merged.**
> Ewl 3373 hub page

- styleguide/source/_patterns/01-molecules/08-lists/10-list-subcategory/_list-subcategory.scss
- styleguide/source/_patterns/01-molecules/08-lists/10-list-subcategory/list-subcategory.md
- styleguide/source/_patterns/01-molecules/08-lists/10-list-subcategory/list-subcategory.twig
- styleguide/source/assets/css/scss/generic/_typography.scss
- styleguide/source/assets/css/style.scss
To review, go to Molecules > Lists > Subcategory List
> Create and style subcategory list component

- .github/PULL_REQUEST_TEMPLATE.md
https://issues.ama-assn.org/browse/EWL-3454
Adds the pull request template we are using for the Corporate repository to the style guide repository.
> EWL-3454: adds the pull request template to the style guide repo.

- styleguide/source/_patterns/00-atoms/03-links/04-link-primary-nav.twig
- styleguide/source/_patterns/00-atoms/04-images/00-logo.twig
- styleguide/source/_patterns/01-molecules/05-navigation/00-primary-nav/_primary-nav.scss
- styleguide/source/_patterns/01-molecules/05-navigation/00-primary-nav/primary-nav.twig
- styleguide/source/_patterns/03-templates/01-home/01-home.twig
- styleguide/source/_patterns/04-pages/00-primary-landing-page/about.twig
- styleguide/source/_patterns/04-pages/00-primary-landing-page/delivering-care.twig
- styleguide/source/_patterns/04-pages/00-primary-landing-page/education.twig
- styleguide/source/_patterns/04-pages/00-primary-landing-page/life-career.twig
- styleguide/source/_patterns/04-pages/00-primary-landing-page/practice-management.twig
- styleguide/source/assets/css/style.scss
- styleguide/source/assets/js/nav-primary.js
- [EWL-3405: HOD Callouts | Navigation](https://issues.ama-assn.org/browse/EWL-3405)
Think it would be ideal to deploy this somehow in order to test on actual test device, or can try using Safari Web Inspector. https://developer.apple.com/library/content/documentation/AppleApplications/Conceptual/Safari_Developer_Guide/GettingStarted/GettingStarted.html
This changes the main navigation to be hover at 740px+
I tried to maintain on click functionality as well. I need to discuss more with Andy about his expectations around when this shifts form hover to on click and how that works.
> EWL-3405 Begin to implement hover state on navigation

- styleguide/source/_patterns/00-atoms/04-images/00-logo.twig
- styleguide/source/_patterns/02-organisms/00-global/01-single-task-header/_single-task-header.scss
- styleguide/source/_patterns/02-organisms/00-global/01-single-task-header/single-task-header.md
- styleguide/source/_patterns/02-organisms/00-global/01-single-task-header/single-task-header.twig
- styleguide/source/assets/css/style.scss
- [EWL-3267: Single Task Header](https://issues.ama-assn.org/browse/EWL-3267)
Adds a new pattern (organism) for Single Task Header
N/A
None
No
---
> [EWL-3267] : creates a single task header pattern

- styleguide/source/_patterns/00-atoms/03-links/02-link-black.twig
- styleguide/source/_patterns/01-molecules/08-lists/11-list-events/_list-events.scss
- styleguide/source/_patterns/01-molecules/08-lists/11-list-events/list-events.md
- styleguide/source/_patterns/01-molecules/08-lists/11-list-events/list-events.twig
- styleguide/source/assets/css/style.scss
- [EWL-3272: Events](https://issues.ama-assn.org/browse/EWL-3272)
Adds molecule for Events list.
N/A
N/A
None.
No.
---
> [EWL-3272] : creates Events list molecule

- README.md
NA
- NA
- NA
As discussed in Slack, the README assumes you have gulp installed globally. This corrects that assumption and provides instruction for users who would prefer not to do that. 
If you really want you could remove gulp from your machine, but you prob don't need to.
NA
> Update README with gulp instructions

- styleguide/source/_patterns/01-molecules/06-components/14-audience-hero-subcategory-links/_audience-hero-subcategory-links.scss
- styleguide/source/_patterns/01-molecules/06-components/14-audience-hero-subcategory-links/audience-hero-subcategory-links.md
- styleguide/source/_patterns/01-molecules/06-components/14-audience-hero-subcategory-links/audience-hero-subcategory-links.twig
- styleguide/source/assets/css/style.scss
- https://issues.ama-assn.org/browse/EWL-3263
Creates a new component for audiences items with a hero and subcategory links below.
Add a link to the .feature file and also add to the ticket in the Automated Testing field on the JIRA ticket **OR** note why this can not be tested with behat.
---
> EWL-3263 Adds new component for audience hero subcategory with links

- README.md
N/A
Updates Readme with info on how to use nvm to manage node versions
N/A
N/A
N/A
> Updates Readme with instructions about using nvm to manage node versions

- styleguide/source/_patterns/01-molecules/06-components/11-banner-cta/_banner-cta.scss
- styleguide/source/_patterns/01-molecules/06-components/11-banner-cta/banner-cta-no-stacking-left.md
- styleguide/source/_patterns/01-molecules/06-components/11-banner-cta/banner-cta-no-stacking-left.twig
- styleguide/source/_patterns/01-molecules/06-components/11-banner-cta/banner-cta-no-stacking.md
- styleguide/source/_patterns/01-molecules/06-components/11-banner-cta/banner-cta-no-stacking.twig
N/A
- [EWL-3630: Design 50/50 No Stacking Component - style guide](https://issues.ama-assn.org/browse/EWL-3630)
Adds two new components to the Style Guide:
- CTA Banner 50/50 (No Stacking)
- CTA Banner 50/50 (No Stacking) Left
N/A
N/A
> EWL-3630 Create 50/50 "No Stacking" Component

- README.md
- styleguide/docs/code_conventions.md
EWL-3484 Style Guide | Replace placeholder images on style guide
- [EWL-3484: REplace placeholder images](https://issues.ama-assn.org/browse/EWL-3484)
This is preliminary documentation for the placeholder work so we don't generate more bad patterns.
> Add info for placeholder images

- styleguide/source/_patterns/01-molecules/06-components/12-hero-banner/_hero-banner.scss
- styleguide/source/_patterns/01-molecules/09-hub-components/00-hub-hero/hub-hero.twig
- [EWL-3624: Hub | Hero component mobile issue](https://issues.ama-assn.org/browse/EWL-3624)
- [EWL-3704: SG | Hero component mobile issue](https://issues.ama-assn.org/browse/EWL-3704)
Changed background image per instructions in the ticket on mobile sizes. Adjusted font size and button placement to make it all come together a little better.
Related to Corp [https://github.com/AmericanMedicalAssociation/AMA-Corporate-site/pull/1116](https://github.com/AmericanMedicalAssociation/AMA-Corporate-site/pull/1116).
N/A
N/A
> [EWL-3624] : updates hub hero styles per discussion with Andy

- styleguide/source/_patterns/00-atoms/02-text/19-page-title/_page-title.scss
- styleguide/source/_patterns/00-atoms/02-text/19-page-title/page-title.md
- styleguide/source/_patterns/00-atoms/02-text/19-page-title/page-title.twig
- styleguide/source/_patterns/03-templates/04-topic/_topic.scss
- styleguide/source/_patterns/03-templates/04-topic/topic.twig
- styleguide/source/assets/css/style.scss
- [EWL-3836:Topics | SG | Create & Vis. Req.: "Page Title" Pattern](https://issues.ama-assn.org/browse/EWL-3836)
Creates the page title atom, adds it to the topic template, and applies styling.
N/A
N/A
> EWL-3836: adds page title atom.

- styleguide/source/_patterns/01-molecules/06-components/22-article-preview/02-article-preview-related/article-preview-related.md
- styleguide/source/_patterns/01-molecules/06-components/22-article-preview/02-article-preview-related/article-preview-related.twig
- styleguide/source/_patterns/01-molecules/06-components/22-article-preview/article-preview.md
- styleguide/source/_patterns/01-molecules/08-lists/14-list-topic-related-articles/list-topic-related-articles.md
- styleguide/source/_patterns/01-molecules/08-lists/14-list-topic-related-articles/list-topic-related-articles.twig
- styleguide/source/_patterns/02-organisms/06-topic/06-topic-related-articles/topic-related-articles.md
- styleguide/source/_patterns/02-organisms/06-topic/06-topic-related-articles/topic-related-articles.twig
- styleguide/source/_patterns/03-templates/04-topic/topic.twig
- [EWL-3819: Topics | SG | Create: "Related Articles" Pattern](https://issues.ama-assn.org/browse/EWL-3819)
Creates the related article preview molecule variant of article preview, creates the topic related articles list molecule, creates the topic related articles organism, adds the topic related organism to the topic template.
Styling will occur in https://issues.ama-assn.org/browse/EWL-3839
N/A
> EWL-3819: Topics | SG | Create: "Related Articles" Pattern

- styleguide/source/_patterns/02-organisms/05-ec/03-ec-tabs-course-browser/_ec-tabs-course-browser.scss
Related to work previously merged for 
- [EWL-3948: EC Bug - Active state on tabs](https://issues.ama-assn.org/browse/EWL-3948)
Consolidates styles since there were redundant declarations.
N/A
No
No
> [EWL-3948] : cleaning up what I did sloppily the first time

- styleguide/source/_patterns/02-organisms/06-topic/03-topic-membership/_topic-membership.scss
- [EWL-3969: Topics| modify styleguide pattern - MemberPitch ](https://issues.ama-assn.org/browse/EWL-3969)
Updates css so that WYSIWYG editors can add more tags without everything looking fugly.
No
No
> [EWL-3969] : update styles so p and ol tags render correctly

- styleguide/source/_patterns/02-organisms/06-topic/06-topic-promotion/_topic-promotion.scss
- [EWL-3971: Modify Topics promo pattern](https://issues.ama-assn.org/browse/EWL-3971)
Updates css so that WYSIWYG editors can add more tags without everything looking fugly.
No.
No.
> [EWL-3971] : update styles so ul and ol tags render correctly

- styleguide/source/assets/css/style.scss
N/A
N/A
N/A
PR#221 was merged without a crucial fix - the removal of the @import for the old list-related-topic-content module. This removes it!PR 221 was merged without a crucial fix - the removal of the @import for the old list-related-topic-content module. This removes it!
> Removes list-topic-related-content molecule @import.

- README.md
- styleguide/source/_patterns/00-atoms/00-intro/00-intro.twig
NA
NA
Adds badges via http://shields.io/ and updates some documentation
> Add badge to README and intro pattern

- styleguide/docs/code_conventions.md
- styleguide/source/_patterns/00-atoms/04-images/00-logo.twig
- styleguide/source/_patterns/02-organisms/05-ec/02-ec-partner-row/ec-partner-row.twig
- styleguide/source/_patterns/02-organisms/06-topic/03-topic-membership/topic-membership.twig
- styleguide/source/_patterns/02-organisms/06-topic/06-topic-promotion/topic-promotion.twig
NA
NA
I noticed that our releases have some bad errors in them https://github.com/AmericanMedicalAssociation/AMA-style-guide/commit/342eff381b741a738f8b300c8fe7650db5c00815#diff-054ec3338519b2035b678891aea1da52R37 and tracked it down to "link" being a special PatternLab variable http://patternlab.io/docs/data-link-variable.html. This rewrites all references of "link" to "href". It fixes those errors.
- `gulp serve`
- Observe fewer PHP errors (if any)
- Observe the href in the updated patterns is a non-error string now.
Use something like …
> "link" is special to PatternLab, so change it.

- styleguide/npm-shrinkwrap.json
Shrinkfile update to npm-shrinkwrap.json was not done in a prior PR. This PR adds an updated shrinkwrap file.
> Add shrinkwrap file for gulpfile-glob

- styleguide/source/_patterns/03-templates/04-topic/_topic.scss
- styleguide/source/_patterns/03-templates/04-topic/topic.twig
- https://issues.ama-assn.org/browse/EWL-3858
Exploratory PR to satisfy the requirements for [https://issues.ama-assn.org/browse/EWL-3858] Content sort order for mobile.
Uses CSS grid to reorder content when in mobile view
Refer to [http://learncssgrid.com/#grid-container] to learn more about it
> EWL-3858: Mobile sort order of content

- styleguide/source/_patterns/03-templates/04-topic/topic-with-deprecated-patterns.twig
- [EWL-XXXX: Ticket Title](https://issues.ama-assn.org/browse/EWL-XXXX)
https://americanmedicalassociation.github.io/AMA-style-guide/?p=templates-topic-with-deprecated-patterns is missing a class that's breaking the layout. This fixes that. 
- visit the Topics deprecated patterns page, observe it works.
Use something like [Skitch](https://evernote.com/skitch/) or [GIPHY Capture](https://giphy.com/apps/giphycapture) to capture images/gifs to demonstrate …
> Add class to fix broken template.

- styleguide/build.config.json
- styleguide/source/_patterns/02-organisms/00-global/06-wayfinder/wayfinder.js
Adds jquery.cookies.js to drupalfiles to fix D8 javascript issues
> Adds cookies.js to the drupalfiles

- styleguide/package-lock.json
- styleguide/package.json
- [EWL-4277: Update Handlebars](https://issues.ama-assn.org/browse/EWL-4277)
In order to update the outdated dependencies I've had to fork both https://github.com/AmericanMedicalAssociation/gulpicon and https://github.com/AmericanMedicalAssociation/grunticon-lib. These libraries haven't been updated in over a year, but we should still probably periodically check on them to pull updates if they ever happen. 
- `npm install`
- `gulp serve`
- observe icons …
> EWL-4227 Update handlebars

- styleguide/source/_patterns/02-organisms/00-global/06-wayfinder/wayfinder.js
Removes conditional around jquery cookies preventing cookies from getting read.
> removes condition wrapped around cookies prevent them from getting read

- styleguide/source/_patterns/02-organisms/00-global/06-wayfinder/_wayfinder.scss
n/a
Adds padding around wayfinder logo so it doesn't look so terrible.
> Bugfix: Adds padding around wayfinder logo
