- styleguide/source/_meta/_01-foot.twig
- styleguide/source/_patterns/01-molecules/06-components/08-link-more-less/link-more-less.twig
- styleguide/source/_patterns/01-molecules/08-lists/06-list-featured-content-hero/_list-featured-content-hero.scss
- styleguide/source/_patterns/01-molecules/08-lists/06-list-featured-content-hero/list-featured-content-hero.twig
- styleguide/source/assets/js/featured-content.js
Ticket: https://issues.ama-assn.org/browse/EWL-3087
To test:
- Go to http://localhost:3000/?p=organisms-audience-featured-hero
- On initial page load there should only be three featured items showing
- When you click on the "Load more" link at the bottom, it should slide open the remaining items (6)
- The text should change to "Load less" and the icon should be replaced with a minus
- When you click on the "Load less" link the last three items should slide up and the text of the link should change back to "Load more"
@aCyborg the one markup modification I had to do is wrap each item and its horizontal rule into a `div` so I could hide and show based on item count.
> EWL 3087 - Hero featured load more

- styleguide/source/_patterns/00-atoms/06-buttons/01-button-search/_button-search.scss
- styleguide/source/_patterns/01-molecules/02-blocks/00-block-hero/_block-hero.scss
- styleguide/source/_patterns/01-molecules/02-blocks/01-block-promo/_block-promo.scss
- styleguide/source/_patterns/01-molecules/05-navigation/00-primary-nav/_primary-nav.scss
- styleguide/source/_patterns/01-molecules/05-navigation/06-tabs-audience-selector/_tabs-audience-selector.scss
- styleguide/source/_patterns/01-molecules/05-navigation/07-ribbon-dropdown/_ribbon-dropdown.scss
- styleguide/source/_patterns/01-molecules/05-navigation/08-ribbon-user-menu/_ribbon-user-menu.scss
- styleguide/source/_patterns/01-molecules/06-components/05-page-level-search/_page-level-search.scss
- styleguide/source/_patterns/01-molecules/08-lists/07-list-links-social/_list-links-social.scss
- styleguide/source/assets/css/scss/base/_global-classes.scss
- styleguide/source/assets/css/scss/base/_links.scss
Ticket: https://issues.ama-assn.org/browse/EWL-3107
Essentially the rule is:
- All text links should have a `color` transition of 0.3 seconds
- All icon links should have a `fill` transition of 0.3 seconds
- All blocks that are links should have a `background-color` transition of 0.28 seconds
References:
- User stories describing the interactions - https://issues.ama-assn.org/browse/EWL-1380
- Notes with screenshots from Andy - https://issues.ama-assn.org:8446/confluence/display/CW/Hover+and+Click 
To test:
- I'd suggest going to the All page http://localhost:3000/?p=all and hover over EVERYTHING that's a link
- Focus on text links, linked blocks, SVG icons
**_Note: Underline transitions don't have a transition, they just show up_**
> EWL 3107 - Global actions for links

- styleguide/composer.json
- styleguide/composer.lock
- styleguide/source/assets/js/init.js
- styleguide/source/assets/js/nav-primary.js
- styleguide/source/assets/js/nav.js
- styleguide/source/assets/js/search.js
- styleguide/source/assets/js/tabs-audience-selector.js
Prevents jquery conflicts and addresses errors.
1. Navigate to ~/www/AMA-style-guide/styleguide
2. Run `composer install`
3. Run `gulp serve`
4. Navigate to home page template
5. Use small viewport
6. Click on Audience Selector and verify it opens and closes
7. Verify there are no errors in console
8. Click on Atoms > View all
9. Verify that you can see all atoms
> Prevents jquery conflicts.

- styleguide/source/_patterns/01-molecules/05-navigation/06-tabs-audience-selector/_tabs-audience-selector.scss
- styleguide/source/assets/js/featured-content.js
- styleguide/source/assets/js/jump-nav.js
- styleguide/source/assets/js/tabs-audience-selector.js
Ticket: https://issues.ama-assn.org/browse/EWL-3112
To test:
- Go to Organisms > Sections > Audience Selector
- If the viewport is less than 900px wide, the Audience Selector should collapse. You should be able to click on the dropdown and the list will slide animate to open. Clicking the list again will slide close.
- If the viewport is more than 900px wide, the Audience Selector should be visible and display inline.
> EWL - 3112 animate audience selector

- styleguide/source/_patterns/01-molecules/05-navigation/06-tabs-audience-selector/_tabs-audience-selector.scss
- styleguide/source/_patterns/01-molecules/05-navigation/06-tabs-audience-selector/tabs-audience-selector.twig
- styleguide/source/_patterns/01-molecules/08-lists/06-list-featured-content-hero/_list-featured-content-hero.scss
- styleguide/source/_patterns/02-organisms/03-sections/06-audience-featured-hero/_audience-featured-hero.scss
- styleguide/source/_patterns/02-organisms/03-sections/06-audience-featured-hero/audience-featured-hero.twig
- styleguide/source/assets/js/featured-content.js
Ticket: https://issues.ama-assn.org/browse/EWL-3234
Refactored the show hide functionality for the audience selector. Now the user can tab between each audience as well as show and hide featured content.
To test:
- Visit http://localhost:3000/?p=organisms-audience-featured-hero
- Tab through the audience selector and ensure the content changes.
- Click the load more/less link for each audience.
> EWL 3234 - Audience selector featured content

- styleguide/source/_meta/_01-foot.twig
- styleguide/source/_patterns/01-molecules/04-forms/00-search-field/_search-field.scss
- styleguide/source/_patterns/02-organisms/00-global/02-search_modal/_search_modal.scss
- styleguide/source/_patterns/02-organisms/00-global/02-search_modal/search_modal.twig
- styleguide/source/_patterns/03-templates/01-home/01-home.twig
- styleguide/source/assets/js/nav-primary.js
- styleguide/source/assets/js/search-modal.js
Ticket: https://issues.ama-assn.org/browse/EWL-3077
To test:
- Go to http://localhost:3000/?p=templates-home
- Click on the search icon in upper right corner to open the search modal
- When the search modal is opened, the search input should be focused
- Click search icon again to close
- A user should be able to close the search modal by clicking on the close "X" as well
- A user should be able to switch to a primary nav dropdown when the search modal is open by clicking on a top level item
- Check above functionality at all breakpoints
> EWL 3077 - Search modal overlay behavior

- styleguide/source/_patterns/01-molecules/05-navigation/07-ribbon-dropdown/_ribbon-dropdown.scss
Fixed width was causing the arrow to drop to the next line in the the Account Management Center project.
**Before:**
**After**
> Fixes arrow dropping to next line

- styleguide/source/_patterns/01-molecules/05-navigation/06-tabs-audience-selector/tabs-audience-selector.twig
- [EWL-2735: Accessibility | iPhone VoiceOver does not recognized "Find Trusted Info" as a menu](https://issues.ama-assn.org/browse/EWL-2735)
Adds aria roles of menu and menu item to the home page audience selector list and list items in order for screen reader to recognized the items as a menu and not links.
Requires manual testing with a screen reader.
N/A
Will require the audience selector on Corporate to be converted to using the pattern from the style guide.
---
> EWL-2735: adds aria roles to quicktabs for screen reader.

- styleguide/source/_meta/_01-foot.twig
- styleguide/source/_patterns/00-atoms/08-media/01-video-youtube/01-video-youtube.md
- styleguide/source/_patterns/00-atoms/08-media/01-video-youtube/01-video-youtube.twig
- styleguide/source/_patterns/00-atoms/08-media/01-video-youtube/_01-video-youtube.scss
- styleguide/source/_patterns/01-molecules/09-hub-components/01-hub-cta/_hub-cta-half-video.scss
- styleguide/source/_patterns/01-molecules/09-hub-components/01-hub-cta/hub-cta-half-video.md
- styleguide/source/_patterns/01-molecules/09-hub-components/01-hub-cta/hub-cta-half-video.twig
- styleguide/source/_patterns/03-templates/03-hub/hub.twig
- styleguide/source/assets/css/style.scss
- styleguide/source/assets/js/hub-cta-half-video.js
- [EWL-3477: hub add cta 50 50 video component to styleguide](https://issues.ama-assn.org/browse/EWL-3477)
Adds the following:
- Atom: "Video Youtube"
- Molecule: "Hub CTA 50/50 Video"
- Hub CTA 50/50 Video molecule as a newly included pattern in the "Hub" Template
- A JS file, hub-cta-half-video.js, where `.fitvids()` is initialized
The most important thing to do in this ticket was prevent the video and thumbnail from being cropped at any viewpoint. @froboy came up with the solution in the attached screenshot, which uses fitvids() to scale the video responsively. Fitvids.js was included in the codebase already, but was not used in the style guide up to this point.
- Navigate to Atoms > Media > Video - Youtube
- Observe that the Media - Youtube atom exists
- Navigate to Molecules > Hub …
> Ewl 3477 hub add cta 50 50 video component to styleguide

- styleguide/source/_patterns/01-molecules/06-components/10-card-cta/_card-cta.scss
- styleguide/source/_patterns/01-molecules/06-components/12-hero-banner/_hero-banner.scss
- styleguide/source/_patterns/02-organisms/03-sections/01-card-row/_card-row.scss
- styleguide/source/_patterns/02-organisms/04-hub/00-hub-header/_hub-header.scss
- [EWL-3485: Hub | Visual QA Fixes](https://issues.ama-assn.org/browse/EWL-3485)
Various CSS changes in accordance with visual QA.
These changes mirror changes on the Corporate site: https://github.com/AmericanMedicalAssociation/AMA-Corporate-site/pull/1032
Navigate to Templates > Hub > Hub and verify changes are correct according to visual QA:
N/A (why does the SG template have a section for this?)
- Investigate heights of row cards in IE11 - broken out into [EWL-3518](https://issues.ama-assn.org/browse/EWL-3518)
N/A
---
> EWL-3485 Hub | Visual QA Fixes

- styleguide/source/_patterns/01-molecules/06-components/10-card-cta/_card-cta.scss
- [EWL-3518: Hub | Card heights in IE11](https://issues.ama-assn.org/browse/EWL-3518)
This updates the style guide to match the work done in https://github.com/AmericanMedicalAssociation/AMA-Corporate-site/pull/1046.
N/A
N/A
N/A
---
> EWL-3518 Hub | Card heights in IE11

- styleguide/source/_patterns/01-molecules/00-text/00-section-header/_section-header.scss
- [EWL-3526: Article Template in IE11](https://issues.ama-assn.org/browse/EWL-3526)
Basically just adds a width:100% so the layout doesn't collapse in IE11.
N/A
Before:
After:
Should re-check the article template after EWL-3550 and EWL-3551 are completed.
No.
---
> [EWL-3526] : adds a fix for the centered section heading layout in IE11

- styleguide/source/_patterns/00-atoms/04-images/00-logo.twig
- styleguide/source/_patterns/02-organisms/05-ec/02-ec-partner-row/_ec-partner-row.scss
- styleguide/source/_patterns/02-organisms/05-ec/02-ec-partner-row/ec-partner-row.md
- styleguide/source/_patterns/02-organisms/05-ec/02-ec-partner-row/ec-partner-row.twig
- styleguide/source/assets/css/style.scss
- [EWL-3573: EC | Design Partner Logo component](https://issues.ama-assn.org/browse/EWL-3573)
Created a row of linked images per wireframes
None.
Could make molecules for the logo images themselves, but that seemed unnecessary given how simple they are.
> [EWL-3573] : creates a partner logo card row

- styleguide/composer.json
- styleguide/composer.lock
- styleguide/patches/core-builder-scss-files.patch
- styleguide/patches/styleguidekit-index-scss-panel.patch
- [EWL-3093: Get CSS in Tab](https://issues.ama-assn.org/browse/EWL-3093)
Related PR:
- [https://github.com/AmericanMedicalAssociation/AMA-style-guide/pull/144](https://github.com/AmericanMedicalAssociation/AMA-style-guide/pull/144)
Uses patches instead of gulp to achieve scss panel injection.
There are countless improvements that could be made, but probably separate tickets should be made for those
This is a somewhat nicer approach than the gulp, but composer is less predictable about when it recognizes patch updates when you run `composer install`. You sometimes have to purge the libraries to force it to install and patch.
**PR #144 should be closed out if/when this is merged.**
> Ewl 3093 css tab patch

- styleguide/source/_patterns/01-molecules/06-components/10-card-cta/card-cta-no-image.json
- styleguide/source/_patterns/01-molecules/06-components/11-banner-cta/banner-cta-no-stacking-left.twig
- styleguide/source/_patterns/01-molecules/06-components/11-banner-cta/banner-cta-no-stacking.twig
- styleguide/source/_patterns/01-molecules/06-components/12-hero-banner/hero-banner.json
- styleguide/source/_patterns/01-molecules/09-hub-components/00-hub-hero/hub-hero-no-overlay.json
- [EWL-3676: Make sure patterns aren't regressed by removing conditionals in EC patterns](https://issues.ama-assn.org/browse/EWL-3676)
Adds json where placeholder content appeared to express context, otherwise ensures proper defaulting behavior for patterns modified to use json for the Education Center.
~Wait for PR #157 to be merged.~
Review the following patterns and see if placeholder text is acceptable:
N/A
No.
Depends on PR #157 so I've submitted the PR directly to that branch.
> Ewl 3676 add json to regressed patterns

- styleguide/source/_patterns/00-atoms/06-buttons/02-button/button-submit.twig
- [EWL-3814: Remove Button-Submit pattern from style guide](https://issues.ama-assn.org/browse/EWL-3814)
Removed unused pattern button-submit.
N/A
no
no
> [EWL-3814] : removes button-submit pattern

- README.md
- styleguide/source/_patterns/01-molecules/02-blocks/block-cta-with-list/_block-cta-with-list.scss
- styleguide/source/_patterns/01-molecules/06-components/22-article-preview/_article-preview.scss
- styleguide/source/_patterns/01-molecules/08-lists/13-list-topic-related-content/_list-topic-related-content.scss
- styleguide/source/_patterns/02-organisms/06-topic/01-topic-hero/_topic-hero.scss
- styleguide/source/_patterns/02-organisms/06-topic/04-topic-related-content/_topic-related-content.scss
- styleguide/source/_patterns/02-organisms/06-topic/04-topic-topic-articles/_topic-topic-articles.scss
- styleguide/source/_patterns/03-templates/04-topic/_topic.scss
- styleguide/source/assets/css/scss/generic/_mixins.scss
- styleguide/source/assets/css/scss/generic/_variables.scss
- styleguide/source/assets/css/scss/objects/_layout.scss
- [EWL-3857: Topics | SG | Mobile: "Topic" Template gutter scaling](https://issues.ama-assn.org/browse/EWL-3857)
- Added a new mixin, `gutter()`, to use in conjunction with SCSS variables that contain a list of properties to define the desired gutter. Documented in comments in _layout.scss and _mixins.scss
- Implemented the mixin for elements that were already styled with gutters in previous PRs
N/A
N/A
> EWL-3857 Topics | SG | Mobile: "Topic" Template gutter scaling

- styleguide/gulpfile.js
NA
NA
- [EWL-3815: Ticket Title](https://issues.ama-assn.org/browse/EWL-3815)
As per https://github.com/AmericanMedicalAssociation/ama-d8/pull/17#pullrequestreview-53622324, change name of the JS file that's generated for drupal.
- `gulp serve`
- observe `public/assets/js/styleguide-custom.js` exists instead of `drupal.js`
> Give custom JS a better name.

- styleguide/source/_patterns/03-templates/04-topic/_topic.scss
- styleguide/source/assets/js/fitvids.js
- [EWL-3861: Topics | SG | Regression: Set a height/min-height for videos](https://issues.ama-assn.org/browse/EWL-3861)
Adjusts the multiplier for the calculated padding applied to videos.
N/A
N/A
> EWL-3861: Topics | SG | Regression: Set a height/min-height for videos

- styleguide/source/_patterns/02-organisms/06-topic/07-topic-email-subscription/topic-email-subscription.md
- styleguide/source/_patterns/03-templates/04-topic/topic.twig
- [EWL-3882: Topics | SG | Remove Email Subscription pattern from Topic template](https://issues.ama-assn.org/browse/EWL-3882)
Removes the Email Subscription from the Topic template pattern. Documents the reason why in the `.md` file for that pattern.
N/A
N/A
N/A
> EWL-3882 Topics | SG | Remove Email Subscription pattern from Topic template

- styleguide/source/_patterns/01-molecules/01-layouts/deprecated/03-layout-three-up/_layout-three-up.scss
- styleguide/source/_patterns/01-molecules/01-layouts/deprecated/03-layout-three-up/layout-three-up.twig
- styleguide/source/_patterns/01-molecules/01-layouts/deprecated/08-layout-four-up/_layout-four-up.scss
- [EWL-3838: SG | Clean up use of grid() mixin to use .grid class instead](https://issues.ama-assn.org/browse/EWL-3838)
The `layout` class provides the `@include grid();` mixin for use. Removes the `grid();`  from being used directly in layouts. 
Note: This work is part of the layout refactoring effort.
N/A
N/A
N/A
> EWL-3838: removes grid mixin directly used in layouts.

- styleguide/source/_patterns/01-molecules/12-ec/00-ec-card-course/_ec-card-course.scss
- styleguide/source/_patterns/01-molecules/12-ec/02-ec-card-course-bundle/_ec-card-course-bundle.scss
- [EWL-3869: Card heights should be equal to tallest card](https://issues.ama-assn.org/browse/EWL-3869)
EC Course bundle cards and course card rows did not expand to the height of the tallest card. Added a `height: 100%` style to fix this.
Issue:
Fix: 
Add to Corporate
N/A
> [EWL-3869] : adds a height to ec cards so they expand to the tallest

- styleguide/docs/git-workflow.md
N/A
Edits @deadarm's previous git documentation to remove git rebase vs merge discussion for the time being. The documentation was not sufficiently clear about where rebasing should fit into our workflow and the team needs to discuss if this workflow is suitable for us without Megh being able to provide guidance on its use.
Also revises explanation of pull vs fetch since existing discussion was somewhat misleading.
> Removes references to git rebase until further discussion with AMA team

- styleguide/source/_patterns/01-molecules/06-components/22-article-preview/article-preview.twig
- [EWL-3765: Topics | Theme News Article](https://issues.ama-assn.org/browse/EWL-3765)
While working on https://github.com/AmericanMedicalAssociation/ama-d8/pull/52 it started to become clear that the `<p>`s of `body` should be inside a `<div>` container, and that the container should have the `.topic_article-preview_description` class rather than the individual paragraphs.
...
...
...
...
> [EWL-3765] move <p>s inside the .topic_article-preview_description container

- styleguide/source/_meta/_00-head.twig
- [EWL-3977: SG | Change Typekit to CSS](https://issues.ama-assn.org/browse/EWL-3977)
Removes js call to Typekit. Adds css link to Typekit.
N/A
No.
No.
> [EWL-3977] switch from js to css implementation of Typekit

- styleguide/source/_patterns/02-organisms/06-topic/01-topic-hero/_topic-hero.scss
- [EWL-3974: Topics | CSS line height for Topic hero title](https://issues.ama-assn.org/browse/EWL-3974)
Adds css specified in the ticket
Inspect title and see the line height is 1.11765
N/A
N/A
N/A
> [EWL-3974] : adds specified line height to topics hero h2

- styleguide/gulpfile.js
NA
NA
Follow up to #213, which didn't actually work as expected. Since gulp wants to run everything asynchronously all the time ever which is super annoying, we have to combine what was going on in `gulp release` into a single `runSequence` command (also prob because my gulp-ing is bad). I've tested and this works now.
- Be sure the last commit in your branch (before the gulp changes) is https://github.com/AmericanMedicalAssociation/AMA-style-guide/commit/e2350cb04a0daf37054e91f84dfa4cbd81a422f7
- Run `gulp release`
- Observe a commit to `gh-pages` and …
> Run release in single sequence because gulp is annoying.

- styleguide/docs/code_conventions.md
- styleguide/gulpfile.js
- styleguide/package.json
- styleguide/source/_patterns/01-molecules/06-components/11-banner-cta/_banner-cta.scss
- styleguide/source/_patterns/01-molecules/06-components/18-people-bio/_people-bio.scss
- styleguide/source/_patterns/01-molecules/08-lists/11-list-events/_list-events.scss
- styleguide/source/_patterns/01-molecules/11-account-mgmt-center/01-block-select/_block-select.scss
- styleguide/source/_patterns/02-organisms/06-topic/03-topic-membership/_topic-membership.scss
- styleguide/source/_patterns/02-organisms/06-topic/06-topic-promotion/_topic-promotion.scss
- styleguide/source/assets/css/pattern-scaffolding.scss
- styleguide/source/assets/css/scss/base/_forms.scss
- [EWL-3909: Style guide is not running Scss linter on gulp serve](https://issues.ama-assn.org/browse/EWL-3909)
Adds the `stylelint` task to the `serve` task
Cleans up existing errors when the linter runs
N/A
No
No
> Ewl 3909 gulp linter

- styleguide/source/_patterns/02-organisms/06-topic/01-topic-hero/_topic-hero.scss
- [EWL-3996: Topics | SG | ENHANCEMENT | Hide "Topic Labels" on mobile in Article Hero block.](https://issues.ama-assn.org/browse/EWL-3996)
Adds a display: none and removes excess top margin when breakpoint is between 0 and our tablet breakpoint.
Before
After
No
No
> [EWL-3996] : adds mobile styles for hiding the topic label

- styleguide/source/_patterns/01-molecules/06-components/22-article-preview/article-preview.twig
**JIRA ticket**
* [EWL-4017: Topics | Reorder components in Hero](https://issues.ama-assn.org/browse/EWL-4017)
Update the article-preview.twig file so the order for the elements is always as follows:
1. Media (image or video)
2. Title
3. Description
**Before**
-----
**After***
N/A
N/A
> refs EWL-4017: ensure that order is always media, title then description

- docs/code_conventions.md
- [EWL-4005: SPIKE Define line ending standards for Twig](https://issues.ama-assn.org/browse/EWL-4005)
Define what the coding standard will be for newlines at the end of Twig files: we will use newlines at the end of Twig files. And decide on a remediation strategy for the current Twig files: we will not be remediating current Twig files, but we should be adding a newline at then end of Twig files going forward.
Use something like …
> refs EWL-4005: update to docs about newline and coding standards

- styleguide/source/_patterns/01-molecules/08-lists/12-list-topic-tools/_list-topic-tools.scss
- styleguide/source/_patterns/01-molecules/08-lists/12-list-topic-tools/list-topic-tools.json
- [EWL-4110: Topics | Clean up tools text wrap](https://issues.ama-assn.org/browse/EWL-4110)
Adjusts the height of the icon in the Tools block so that two-line text wraps more cleanly.
before:
after:
In order to support more than two lines of tool text this pattern would probably need to be refactored. Workaround per convo with @froboy is to suggest a character limit in the field help text.
> [EWL-4110] Topics | Clean up tools text wrap

- styleguide/source/assets/css/scss/objects/_layout.scss
- [EWL-3809: Topics | Theme Footer](https://issues.ama-assn.org/browse/EWL-3809)
- adds `width: 100%;` to `.col-width-12` grid class because IE11 doesn't respect nested flexbox elements sometimes. See https://github.com/philipwalton/flexbugs/issues/104
Before:
After:
- this will need to be deployed to `dev-assets` and consumed by d8 before it can be tested/pass in d8.
Found some other broken things (header, page container) and am following up about fixing those as separate tickets with Gwen.
> [EWL-3809] Fix footer in IE11

- styleguide/source/_patterns/01-molecules/05-navigation/08-ribbon-user-menu/_ribbon-user-menu.scss
- [EWL-3792: Topics | Build Ribbon Header](https://issues.ama-assn.org/browse/EWL-3792)
Bumped up the width of the User Menu element by a few pixels. For some reason IE11 didn't think the menu was wide enough. May have to do with subpixel rendering? Anyway, it works now... 
Before:
After:
- this needs to be deployed to `dev-assets` and consumed by drupal before this can be tested in d8.
N/A
> [EWL-3792] Topics | Build Ribbon Header

- styleguide/source/_patterns/03-templates/04-topic/_topic.scss
- [EWL-3951: Topics | Theme "bookend" layout](https://issues.ama-assn.org/browse/EWL-3951)
Adds `display: block;` to the `.topic` page container in to fix a display bug in IE11. 
For some reason IE11 wasn't rendering`div.topic` as block-level despite this being a standard of how the DOM works... probably something to do with Flexbox and inheritance (I couldn't find a specific example of this bug happening elsewhere but there are [related reports on SO having to do with ancestry](https://stackoverflow.com/questions/44243712/ie11-css-display-inline-block-overflowing-inside-flexbox)) 
Before:
After:
This will need to be deployed to `dev-assets` and consumed by d8 before the changes can be tested in Drupal. 
N/A
> [EWL-3951] Topics | fix "bookend" layout in IE11

- styleguide/source/_patterns/03-templates/04-topic/topic.twig
- [EWL-4022: SG | Remove ".topic_bottom" region from Topic template](https://issues.ama-assn.org/browse/EWL-4022)
Removes the `.topic_bottom` region from the template as it isn't being used.
N/A
N/A
This has no d8 implications - it's just cleanup.
> [EWL-4022] SG | Remove ".topic_bottom" region from Topic template

- styleguide/source/_patterns/01-molecules/06-components/22-article-preview/_article-preview.scss
- [EWL-4139: Bug - topic page text is only going to 50% width on mobile](https://issues.ama-assn.org/browse/EWL-4139)
- Adds a sibling selector to the Related Articles block list items so that if there's no image, the text will span full width.
Deleting the image from the block on mobile
This needs to be released via `gulp-deploy` and consumed by d8 before it can be tested there.
N/A
> [EWL-4139] Bug - topic page text is only going to 50% width on mobile

- styleguide/source/_patterns/00-atoms/06-buttons/01-button-search/_button-search.scss
- styleguide/source/_patterns/00-atoms/09-icons/05-search.twig
- https://issues.ama-assn.org/browse/EWL-3937
Removes data-grunticon-embed class because it overrides the search icon background image.
> Bugfix: EWL-3937 Regression in search icon

- styleguide/source/_patterns/01-molecules/08-lists/14-list-topic-related-articles/_list-topic-related-articles.scss
- styleguide/source/_patterns/01-molecules/08-lists/14-list-topic-related-articles/list-topic-related-articles.twig
- https://issues.ama-assn.org/browse/EWL-4231
Remove `<LI>` in favor of markup we can use on the Drupal side -- We need to be able to use multiple "View Modes" in one section. On the Drupal side, when using this with other View Modes we were getting `<li>` without a parent `<ul>`.
> EWL 4231: Remove LIs

- styleguide/source/_patterns/01-molecules/04-forms/01-form-item/_form-item.scss
- [EWL-4239: Style Guide | Eye icon color incorrect](https://issues.ama-assn.org/browse/EWL-4239)
Eye color incorrect for password input fields. It should be grey when not in focus and black when in focus.
N/A
---
> EWL-4239 - Fix eye icon color

- styleguide/source/_patterns/01-molecules/00-text/06-link-with-back-icon/_link-with-back-icon.scss
- styleguide/source/_patterns/01-molecules/00-text/06-link-with-back-icon/link-with-back-icon.json
- styleguide/source/_patterns/01-molecules/00-text/06-link-with-back-icon/link-with-back-icon.md
- styleguide/source/_patterns/01-molecules/00-text/06-link-with-back-icon/link-with-back-icon.twig
- styleguide/source/_patterns/02-organisms/00-global/06-wayfinder/_wayfinder.scss
- styleguide/source/_patterns/02-organisms/00-global/06-wayfinder/wayfinder.json
- styleguide/source/_patterns/02-organisms/00-global/06-wayfinder/wayfinder.md
- styleguide/source/_patterns/02-organisms/00-global/06-wayfinder/wayfinder.twig
- styleguide/source/_patterns/02-organisms/00-global/06-wayfinder/wayfinder~referred.json
- styleguide/source/_patterns/03-templates/04-topic/topic.twig
- styleguide/source/_patterns/03-templates/04-topic/topic~with-wayfinder-referred.json
- [EWL-4030: Topics |ENHANCEMENT | SG | Create & Style Wayfinder pattern](https://issues.ama-assn.org/browse/EWL-4030)
- Adds a new organism, "Wayfinder," to the style guide, as well as a "Wayfinder referred" pseudopattern.
- Adds the Wayfinder organism to the main Topic template pattern.
- Adds a "Topic with Wayfinder Referred" pseudopattern in Templates > Topic.
- Adds a new molecule, "Link with 'Back' Icon"
N/A
- I know the empty `.col-width-4` in `wayfinder.twig` being used to preserve whitespace is not ideal, but I wasn't aware of a better solution. Suggestions welcome.
- This currently looks not great IMO at smaller breakpoints. I vaguely recall some kind of decision about Wayfinder not showing up on mobile at all; have reached out to Robert to confirm. In the …
> [EWL-4030] Wayfinder front end

- styleguide/source/_patterns/02-organisms/03-sections/11-state-data-info/state-data-info.json
- styleguide/source/_patterns/02-organisms/03-sections/11-state-data-info/state-data-info.twig
- [EWL-4252: Ticket Title](https://issues.ama-assn.org/browse/EWL-4252)
Use the figure molecule instead of the image atom, since that is what is standard on the corp website.
> EWL-4252: swap out the image atom for the figure molecule

- styleguide/source/_patterns/03-templates/04-topic/_topic.scss
NA
- [EWL-3858: Mobile sort order](https://issues.ama-assn.org/browse/EWL-3858)
It wasn't described well in the ticket and I think we missed this in the review of #255, but the new region was displaying lower on tablet and I think it should be at the top there too. This fixes that behavior.
- Observe the topic-member-right region is at the top of the right sidebar on tablet and desktop, and stacks above all other sidebar content on mobile.
- Observe nothing else breaks.
Use something like [Skitch](https://evernote.com/skitch/) or [GIPHY …
> EWL-3858 Keep member pitch at the top on tablet.

- docs/creating_a_release.md
- styleguide/gulpfile.js
NA
I'm not sure why, but `gulp release` didn't previously push to `dev-assets`. This resulted in more than one instance of releases that didn't include pushes there. This now pushes to all the things on `release`.
- Change line 264 of gulpfile.js to `    .pipe(ghPages({ branch: config.deployment.branch, push: false}));` so that you can test without pushing
- Run `gulp release`
- Observe commits to `dev-assets`, `master`, and `gh-pages`.
Use something like …
> Update release task to push to dev-assets.

- styleguide/source/_patterns/02-organisms/06-topic/10-topic-lead-news/topic-lead-news.json
- styleguide/source/_patterns/02-organisms/06-topic/10-topic-lead-news/topic-lead-news.twig
- [EWL-4344: SG | Topics template doesn't show Lead News title](https://issues.ama-assn.org/browse/EWL-4344)
- Added an include for the block label at the top of the block.
N/A
N/A
> [EWL-4344] SG | Topics template doesn't show Lead News title

- styleguide/source/_patterns/02-organisms/00-global/06-wayfinder/_wayfinder.scss
- styleguide/source/_patterns/02-organisms/00-global/06-wayfinder/wayfinder.js
- styleguide/source/_patterns/02-organisms/00-global/06-wayfinder/wayfinder.twig
- [277: Wayfinder Height](https://github.com/AmericanMedicalAssociation/AMA-style-guide/issues/277)
**Does not have a linked to story because Jira is down!**
- Removes padding and height to wayfinder per UX request
- Wayfinder expands depending on the length of the link content
`    var pageTitle  = document.title.replace(' | AMA', '');
var pageUrl = window.location.href;
$.cookie.json = true;
$.cookie('ama_wayfinder_cookie', [pageTitle, pageUrl], { expires: 1, path: '/'});
`
don't commit it.
This needs to get tested in D8
The wayfinder will not show unless there is a …
> Removes extra padding and height to the wayfinder.
